// Icon import
import { ReactComponent as add } from "./icon/Add.svg";
import { ReactComponent as alarm } from "./icon/Alarm.svg";
import { ReactComponent as alarmNum } from "./icon/AlarmNum.svg";
import { ReactComponent as back } from "./icon/Back.svg";
import { ReactComponent as basicProfile } from "./icon/BasicProfile.svg";
import { ReactComponent as camera } from "./icon/Camera.svg";
import { ReactComponent as chat } from "./icon/Chat.svg";
import { ReactComponent as claim } from "./icon/Claim.svg";
import { ReactComponent as close } from "./icon/Close.svg";
import { ReactComponent as deleteContent } from "./icon/Delete.svg";
import { ReactComponent as deleteImage } from "./icon/DeleteImage.svg";
import { ReactComponent as home } from "./icon/Home.svg";
import { ReactComponent as logo } from "./icon/Logo.svg";
import { ReactComponent as menu } from "./icon/Menu.svg";
import { ReactComponent as myPage } from "./icon/MyPage.svg";
import { ReactComponent as next } from "./icon/Next.svg";
import { ReactComponent as ok } from "./icon/Ok.svg";
import { ReactComponent as open } from "./icon/Open.svg";
import { ReactComponent as search } from "./icon/Search.svg";
import { ReactComponent as send } from "./icon/Send.svg";
import { ReactComponent as share } from "./icon/Share.svg";
import { ReactComponent as write } from "./icon/Write.svg";
import { ReactComponent as kakao } from "./icon/Kakao.svg";
import { ReactComponent as noSearch } from "./icon/NoSearch.svg";
import { ReactComponent as noAlarm } from "./icon/NoAlarm.svg";
import { ReactComponent as notPage } from "./icon/NotPage.svg";
import { ReactComponent as event } from "./icon/Event.svg";
import { ReactComponent as notice } from "./icon/Notice.svg";
import { ReactComponent as questions } from "./icon/Questions.svg";
import { ReactComponent as profileEdit } from "./icon/ProfileEdit.svg";
import { ReactComponent as login } from "./icon/Login.svg";
import { ReactComponent as logout } from "./icon/Logout.svg";
import { ReactComponent as heartFull } from "./icon/HeartFull.svg";
import { ReactComponent as heartEmpty } from "./icon/HeartEmpty.svg";
import { ReactComponent as imgPlus } from "./icon/ImgPlus.svg";
import { ReactComponent as imgDelete } from "./icon/ImgDelete.svg";

// Category import
import { ReactComponent as accessory } from "./category/Accessory.svg";
import { ReactComponent as beauty } from "./category/Beauty.svg";
import { ReactComponent as digital } from "./category/Digital.svg";
import { ReactComponent as hobby } from "./category/Hobby.svg";
import { ReactComponent as homeElectronics } from "./category/HomeElectronics.svg";
import { ReactComponent as interior } from "./category/Interior.svg";
import { ReactComponent as manFashion } from "./category/ManFashion.svg";
import { ReactComponent as sport } from "./category/Sport.svg";
import { ReactComponent as womanFashion } from "./category/WomanFashion.svg";

import { ReactComponent as dobong } from "./region/Dobong.svg";
import { ReactComponent as dongdaemun } from "./region/Dongdaemun.svg";
import { ReactComponent as dongjak } from "./region/Dongjak.svg";
import { ReactComponent as eunpyeong } from "./region/Eunpyeong.svg";
import { ReactComponent as gangbuk } from "./region/Gangbuk.svg";
import { ReactComponent as gangdong } from "./region/Gangdong.svg";
import { ReactComponent as gangnam } from "./region/Gangnam.svg";
import { ReactComponent as gangseo } from "./region/Gangseo.svg";
import { ReactComponent as geumcheon } from "./region/Geumcheon.svg";
import { ReactComponent as guro } from "./region/Guro.svg";
import { ReactComponent as gwanak } from "./region/Gwanak.svg";
import { ReactComponent as gwangjin } from "./region/Gwangjin.svg";
import { ReactComponent as jongno } from "./region/Jongno.svg";
import { ReactComponent as jung } from "./region/Jung.svg";
import { ReactComponent as jungnang } from "./region/Jungnang.svg";
import { ReactComponent as mapo } from "./region/Mapo.svg";
import { ReactComponent as nowon } from "./region/Nowon.svg";
import { ReactComponent as seocho } from "./region/Seocho.svg";
import { ReactComponent as seodaemun } from "./region/Seodaemun.svg";
import { ReactComponent as seongbuk } from "./region/Seongbuk.svg";
import { ReactComponent as seongdong } from "./region/Seongdong.svg";
import { ReactComponent as seoul } from "./region/Seoul.svg";
import { ReactComponent as songpa } from "./region/Songpa.svg";
import { ReactComponent as yangcheon } from "./region/Yangcheon.svg";
import { ReactComponent as yeoungdeongpo } from "./region/Yeoungdeongpo.svg";
import { ReactComponent as yongsan } from "./region/Yongsan.svg";

// Logo import
import { ReactComponent as logoClassic } from "./logo/LogoClassic.svg";
import { ReactComponent as logoWood } from "./logo/LogoWood.svg";
import { ReactComponent as logoSilver } from "./logo/LogoSliver.svg";
import { ReactComponent as logoGold } from "./logo/LogoGold.svg";
import { ReactComponent as logoRainbow } from "./logo/LogoRainbow.svg";

import { ReactComponent as eventImg } from "./EventImg.svg";
import { ReactComponent as infoImg } from "./InfoImg.svg";
import { ReactComponent as loadingImg } from "./icon/LoadingImg.svg";

// icon
export const Add = add;
export const Alarm = alarm;
export const AlarmNum = alarmNum;
export const Back = back;
export const BasicProfile = basicProfile;
export const Camera = camera;
export const Chat = chat;
export const Claim = claim;
export const Close = close;
export const Delete = deleteContent;
export const DeleteImage = deleteImage;
export const Home = home;
export const Logo = logo;
export const Menu = menu;
export const MyPage = myPage;
export const Next = next;
export const Ok = ok;
export const Open = open;
export const Search = search;
export const Send = send;
export const Share = share;
export const Write = write;
export const Kakao = kakao;
export const NoSearch = noSearch;
export const NoAlarm = noAlarm;
export const NotPage = notPage;
export const Event = event;
export const Notice = notice;
export const Questions = questions;
export const ProfileEdit = profileEdit;
export const Login = login;
export const Logout = logout;
export const HeartFull = heartFull;
export const HeartEmpty = heartEmpty;
export const ImgPlus = imgPlus;
export const ImgDelete = imgDelete;

// category
export const Accessory = accessory;
export const Beauty = beauty;
export const Digital = digital;
export const Hobby = hobby;
export const HomeElectronics = homeElectronics;
export const Interior = interior;
export const ManFashion = manFashion;
export const Sport = sport;
export const WomanFashion = womanFashion;

// region
export const Seoul = seoul;
export const Dobong = dobong;
export const Dongdaemun = dongdaemun;
export const Dongjak = dongjak;
export const Eunpyeong = eunpyeong;
export const Gangbuk = gangbuk;
export const Gangdong = gangdong;
export const Gangnam = gangnam;
export const Gangseo = gangseo;
export const Geumcheon = geumcheon;
export const Guro = guro;
export const Gwanak = gwanak;
export const Gwangjin = gwangjin;
export const Jongno = jongno;
export const Jung = jung;
export const Jungnang = jungnang;
export const Mapo = mapo;
export const Nowon = nowon;
export const Seocho = seocho;
export const Seodaemun = seodaemun;
export const Seongbuk = seongbuk;
export const Seongdong = seongdong;
export const Songpa = songpa;
export const Yangcheon = yangcheon;
export const Yeoungdeongpo = yeoungdeongpo;
export const Yongsan = yongsan;

// 3d hammer
export const LogoClassic = logoClassic;
export const LogoWood = logoWood;
export const LogoSilver = logoSilver;
export const LogoGold = logoGold;
export const LogoRainbow = logoRainbow;

export const EventImg = eventImg;
export const InfoImg = infoImg;
export const LoadingImg = loadingImg;
