import { ReactComponent as add } from "./Add.svg";
import { ReactComponent as alarm } from "./Alarm.svg";
import { ReactComponent as alarmNum } from "./AlarmNum.svg";
import { ReactComponent as back } from "./Back.svg";
import { ReactComponent as camera } from "./Camera.svg";
import { ReactComponent as chat } from "./Chat.svg";
import { ReactComponent as claim } from "./Claim.svg";
import { ReactComponent as close } from "./Close.svg";
import { ReactComponent as deleteContent } from "./Delete.svg";
import { ReactComponent as deleteImage } from "./DeleteImage.svg";
import { ReactComponent as home } from "./Home.svg";
import { ReactComponent as logo } from "./Logo.svg";
import { ReactComponent as menu } from "./Menu.svg";
import { ReactComponent as myPage } from "./MyPage.svg";
import { ReactComponent as next } from "./Next.svg";
import { ReactComponent as ok } from "./Ok.svg";
import { ReactComponent as open } from "./Open.svg";
import { ReactComponent as search } from "./Search.svg";
import { ReactComponent as send } from "./Send.svg";
import { ReactComponent as share } from "./Share.svg";
import { ReactComponent as write } from "./Write.svg";

export const Add = add;
export const Alarm = alarm;
export const AlarmNum = alarmNum;
export const Back = back;
export const Camera = camera;
export const Chat = chat;
export const Claim = claim;
export const Close = close;
export const Delete = deleteContent;
export const DeleteImage = deleteImage;
export const Home = home;
export const Logo = logo;
export const Menu = menu;
export const MyPage = myPage;
export const Next = next;
export const Ok = ok;
export const Open = open;
export const Search = search;
export const Send = send;
export const Share = share;
export const Write = write;
